### ISSUE TITLE
Missing "$" in telegraf.conf

### ISSUE THREAD

**Issue by diverjoe** [janvda/balena-arm-TIG-monitoring#12]
I believe that there is a missing "$" in the telegraf.conf file on line 53.

flush_interval = "flush_interval"

It seems it should be 
flush_interval = "$flush_interval"

I discovered this when I had been using a fork from your project and then pulled in your changes.  The build no longer started Telegraf properly.   I added the $ and it started working perfectly again.

BTW - this is incredibly amazing!!!!!

**Comment by janvda** [comment]
Many thanks for the comment. 
I have been a bit too quick when making those changes.

I have fixed it : b2031c276ba20d12aee740fe44ed7312a84df6a2
