### ISSUE TITLE
Node-RED readonly

### ISSUE THREAD

**Issue by owarek** [janvda/balena-arm-TIG-monitoring#13]
When I want to change backlight of RPi display, it trhrows:
`Error: EROFS: read-only file system, open '/sys/class/backlight/rpi_backlight/bl_power`

Is there a way to do this on readonly FS or how do I change the FS to writable?

Thank you in advance.

**Comment by janvda** [comment]
Hi @owarek,

I don't think that this question is very specific to this repository.
This repository  even doesn't require any display to be connected to the raspberry pi.

I suggest that you ask this question in the balena forum https://forums.balena.io/

Maybe also have a look at : 
- https://forums.balena.io/t/basic-web-frame-question/4705/53

kr
jan

**Comment by owarek** [comment]
OK
